---
- hosts: all
  become: yes
  tasks:
  - copy:
       src: "{{ deploy_artifact_file }}"
       dest: "{{ dest_remote_dir }}"
       owner: tomcat
       group: tomcat
    notify:
    - restart tomcat
  handlers:
  - name: restart tomcat
    service:
       name: "{{ remote_service }}"
       state: restarted
